use_frameworks!

platform :ios, '11.0'

target 'WTestPostalModule_Example' do
  pod 'WTestPostalModule', :path => '../'
  pod 'WTestToolKit', :git => 'git@github.com:Jeffersons/WTestToolKit.git', branch: 'develop'
  pod 'WTestPostalModule', :path => '../', :testspecs => ['Tests']

  target 'WTestPostalModule_Tests' do
    inherit! :search_paths
  end
end
